Выпиливает всю сборку, сотавляет только статику
htmlacademy/codeguide pull request #13
Opened 2017-04-21 15:50 UTC by juwain

2017-05-26 12:39 UTC, meritt commented
Изометрия на фоне сломалась.

<img width="1258" alt="screen shot 2017-05-26 at 15 39 21" src="https://cloud.githubusercontent.com/assets/10909/26494854/82c1ca6a-4229-11e7-82a3-64a221e4eba0.png">

2017-05-26 12:40 UTC, meritt approved these changes

2017-07-10 10:36 UTC, o0 requested changes
Еще где-то видел забытую инструкцию ESLint и вообще надо причесать. Я займусь!

2017-07-10 10:36 UTC, o0 commented on index.html
> +              <img src="img/logo-html.svg" alt="Логотип HTML">
HTML?

2017-07-10 10:36 UTC, o0 commented on index.html
> +              <img src="img/logo-js.svg" alt="Логотип JavaScript">
JavaScript? Это же нужно для читалок, прикинь человек останавливается на ссылке, которая ведет на гайд по JS, а читалка ему «логотип JS»

2017-07-10 10:36 UTC, o0 commented on javascript.html
> +- if (condition)
Ну, я использовал diff из-за встроенной подсветки зелененьким и красненьким. Если у нас получилось что мы просто используем синтаксис js и ---, +++, то я переделаю на блоки с разным цветом.

2017-07-10 10:36 UTC, o0 commented on javascript.html
> +              <h4>Массивы</h4>
Ой 🙊  Надо что-то сюда написать или убрать заголовок.

2017-07-10 10:40 UTC, juwain commented on javascript.html
> +- if (condition)
Я добавлю для diff стили, оказалось, что их нет по умолчанию.

2017-07-10 10:41 UTC, o0 commented on javascript.html
> +- if (condition)
Не, не надо, я тут подумал, что JS с разным фоном будет лучше. Diff хак

2017-07-10 10:42 UTC, juwain commented on javascript.html
> +- if (condition)
Окей

2017-07-10 10:54 UTC, juwain commented on index.html
> +              <img src="img/logo-js.svg" alt="Логотип JavaScript">
Что-то мне стало казаться, что надо вообще выкинуть эту страницу. Будет две страницы: кодгайд по HTML/CSS и по Javascript. С обеих страниц будут ссылки друг на друга. Получается разводящей страницы не нужно (по крайней мере пока их не стало много).

2017-07-10 11:44 UTC, o0 commented on index.html
> +              <img src="img/logo-js.svg" alt="Логотип JavaScript">
Не знаю, я б оставил;)

2017-07-18 10:22 UTC, o0 commented
@zeckson читани пожалуйста файл `javascript.html`? Это расшифровка конфига ESLInt. Надо уже катить, сколько лет ждем;) Я хочу добавить еще строчку про приоритет версий, что желательно использовать ES6, но если совсем плохо с поддержкой, то можно ES5.

2017-07-18 13:00 UTC, zeckson commented
Надо md закилять или синхронизировать

2017-07-18 14:00 UTC, o0 commented
Закилято!

2017-07-19 13:45 UTC, zeckson requested changes

2017-07-19 13:45 UTC, zeckson commented on md/syntax.md
> +# Стиль кода JS
Почему это не удалено?

2017-07-19 13:45 UTC, zeckson commented on md/syntax.md
> +Строки более 80 символов длиной, снижают скорость чтения заставляя читатаеля
Пруф или не было!

2017-07-19 13:45 UTC, zeckson commented on md/syntax.md
> +Трудоемкий и очень хрупкий процесс. Если хотя бы одна из переменных
`Если хотя бы одна из переменных` что? Аааааа!!! Интрига!

2017-07-19 13:45 UTC, zeckson commented on md/syntax.md
> +#### Аргументы функций и вызовы через цепчку отделяются четырьмя пробелами
У нас в `eslint` двумя. Настало время определиться:
```
'indent': ['error', 2, {
      SwitchCase: 1,
      // continuation indent
      VariableDeclarator: 1, // indent is multiplier * indent = 1 * 2
      MemberExpression: 2, // indent is multiplier * indent = 1 * 2
      FunctionDeclaration: {parameters: 2},
      FunctionExpression: {parameters: 2},
      CallExpression: {arguments: 2}
    }],
```

2017-07-19 13:45 UTC, zeckson commented on md/syntax.md
> +#### Альтернативный способ переносить аргументы — выравнивать их с открывающей скобкой
Хмммм...

2017-07-19 13:45 UTC, zeckson commented on md/syntax.md
> +строка, а у чейнов — последняя и после сортировки и удаления нужно перепроверить
```
последняя и после сортировки и удаления нужно перепроверить получившийся список на валидность.
```
это про что?

2017-07-19 13:45 UTC, zeckson commented on md/syntax.md
> +## Правила языка
Уточнить — для ES без модулей

2017-07-19 13:45 UTC, zeckson commented on md/syntax.md
> +Положительный побочный эффект такого стиля заключается в том,
Мне кажется это лишнее для стайлгайда. Это же не методическое пособие.

2017-07-19 13:45 UTC, zeckson commented on md/syntax.md
> +### Замыкания
Это чё?

2017-07-19 13:46 UTC, zeckson commented
Очень плохой пулл-реквест — в нём свалено всё и изменения и рефакторинги и правки и черт в ступе. Пожалуйста не делайте так. Никакого хорошего ревью не получится

2017-07-19 13:47 UTC, o0 commented on md/syntax.md
> +# Стиль кода JS
Потому что это то, что будет основной версией.

2017-07-19 13:47 UTC, o0 commented on md/syntax.md
> +Строки более 80 символов длиной, снижают скорость чтения заставляя читатаеля
Оке, я поищу

2017-07-19 13:47 UTC, zeckson commented
>  Я хочу добавить еще строчку про приоритет версий, что желательно использовать ES6, но если совсем плохо с поддержкой, то можно ES5.

Давай не будет добавлять такую строчку.

2017-07-19 13:47 UTC, o0 commented on md/syntax.md
> +Трудоемкий и очень хрупкий процесс. Если хотя бы одна из переменных
Тут надо просто показать пример.

2017-07-19 13:47 UTC, o0 commented on md/syntax.md
> +#### Аргументы функций и вызовы через цепчку отделяются четырьмя пробелами
Как тебе нравится?

2017-07-19 13:47 UTC, o0 commented on md/syntax.md
> +#### Альтернативный способ переносить аргументы — выравнивать их с открывающей скобкой
Java-Java.

2017-07-19 13:47 UTC, meritt commented
Я согласен с @zeckson. Сейчас это не вмёржить уже. Можно было сделать ветку от этой ветки.

2017-07-19 13:48 UTC, o0 commented on md/syntax.md
> +строка, а у чейнов — последняя и после сортировки и удаления нужно перепроверить
я когда писал так ощущал, а теперь не думаю вообще, что перенос точки проблема. Даже грешным делом начал подумывать удалить и разрешить все это безобразие. Как ты думаешь?

2017-07-19 13:49 UTC, o0 commented on md/syntax.md
> +Положительный побочный эффект такого стиля заключается в том,
Мне кажется, что почему бы и нет.

2017-07-19 13:51 UTC, o0 commented
Ну если только по тексту то надо было обсуждать в другой ветке, это уже версия, которую @juwain готовит к публикации. Может быть да, можно было сделать в несколько шагов, но сейчас уже PR какой есть, надо что-то делать. Ок, плохо, выход какой? Никаких альтернатив не предложено. Повздыхали и разошлись.

2017-07-19 13:52 UTC, o0 commented
> Давай не будет добавлять такую строчку.

Аргументы и альтернатива. Давай не добавлять такую строку _~потому что это ложь~_, а вместо этого лучше _~напьемся~_

2017-07-19 14:23 UTC, zeckson requested changes

2017-07-19 14:23 UTC, zeckson commented on javascript.html
> +              <li>В качестве символа строки используется стандартный символ, который используется в системе</li>
Это чё?

2017-07-19 14:23 UTC, zeckson commented on javascript.html
> +              <li>После двоеточий и точек с запятым ставятся пробелы. Перед ними — не ставятся.</li>
Где-то есть точки в конце, где-то нет — лучше определиться

2017-07-19 14:23 UTC, zeckson commented on javascript.html
> +              <li>Оператор вызова функции () не отделяется круглыми скобками от названия функции</li>
Имется ввиду вот это: `(callFun)()`

2017-07-19 14:23 UTC, zeckson commented on javascript.html
> +              <li>при объявлении анонимных функций, скобки с параметрами ставятся непосредственно после ключевого слова function. Если функция именована, перед названием ставится пробел, после — нет.
С большой буквы

2017-07-19 14:23 UTC, zeckson commented on javascript.html
> +              <li>при объявлении анонимных функций, скобки с параметрами ставятся непосредственно после ключевого слова function. Если функция именована, перед названием ставится пробел, после — нет.
В нашем `eslint` это не так.

2017-07-19 14:23 UTC, zeckson commented on javascript.html
> +              <li>Звездочка после ключевого слова yield не отбивается пробелом. После звездочки проблел ставится всегда.</li>
`проблел`

2017-07-19 14:23 UTC, zeckson commented on javascript.html
> +              <li>Запрещено называть переменные и свойства ключевыми словами JS</li>
Хорошо бы ссыль

2017-07-19 14:23 UTC, zeckson commented on javascript.html
> +              <li>Все точки с запятой должны быть проставлены явно, не стоит рассчитывать на автоматическую расстановку точек с запятой ASI.</li>
`ASI`?

2017-07-19 14:23 UTC, zeckson commented on javascript.html
> +              <li>Не рекомендуется использовать указатель Unicode BOM в коде, потому что код должен быть сохранен не в кодировке UTF-16, а в кодировке UTF-8, в которой нет указателя порядка бит.</li>
Ссылку бы

2017-07-19 14:23 UTC, zeckson commented on javascript.html
> +              <li>Код работает в строгом режиме: в начале всех файлов явно прописана директива <code>use strict</code>.</li>
`<code>'use strict';</code>`

2017-07-19 14:23 UTC, zeckson commented on javascript.html
> +              <li>В условтях не используется небезопасное отрицание, например использование ! в in или instanceof без скобок.</li>
условтях

2017-07-19 14:23 UTC, zeckson commented on javascript.html
> +              <li>В условтях не используется небезопасное отрицание, например использование ! в in или instanceof без скобок.</li>
Надо как-то единообразно оформить операторы и ключевые слова или все обернуть в `<code></code>` или `<b>` или `<i>`

2017-07-19 14:23 UTC, zeckson commented on javascript.html
> +              <li>Запрещено использовать case без break или return в блоках switch.</li>
Сильное утверждение!

2017-07-19 14:23 UTC, zeckson commented on javascript.html
> +              <li>Запрещено сравнение с NaN. Для проверки, является результат операции числовым, нужно использовать <code>isNaN</code>.</li>
А какой `isNaN` лучше использовать? https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/isNaN или https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Number/isNaN

2017-07-19 14:23 UTC, zeckson commented on javascript.html
> +              <li>Если в функции используется ветвление, в котором есть возврат значения (<code>return</code>), <code>return</code> должен быть добавлен и в остальных ветках. Это правило предотвращае
Примечание автора лучше перенести в конец

2017-07-19 14:23 UTC, zeckson commented on javascript.html
> +}
`;`?

2017-07-19 14:23 UTC, zeckson commented on javascript.html
> +}
`;`?

2017-07-19 14:23 UTC, zeckson commented on javascript.html
> +        <article class="chapter-part">
Ну это вроде как и так запрещено синтаксически. Стилистика тут непричём

2017-07-19 14:23 UTC, zeckson commented on javascript.html
> +              <li>Запрещено использовать множественное объявление через одно ключевое слово. Для каждой переменной используется отдельный <code>var</code>, <code>let</code> или <code>const</code>. Эт
Это уже не так в современных отладчиках. К тому же я бы перенёс примечания автора в конец или выкинул бы совсем

2017-07-19 14:23 UTC, zeckson commented on javascript.html
> +              <li>Запрещено переопределение функций, созданных с помощью функционального объявления (function expression)
`function declaration`

2017-07-19 14:23 UTC, zeckson commented on javascript.html
> +              <li>Вместо коллекции <code>arguments</code>, используется rest-оператор</li>
если позволяет версия языка

2017-07-19 14:23 UTC, zeckson commented on javascript.html
> +              <li>Вместо вызова функции через <code>apply</code> используется spread-оператор</li>
Всмысле всегда юзать `call`?

2017-07-19 14:23 UTC, zeckson commented on javascript.html
> +              <li>bind не используется вне методов классов</li>
Wow! Как теперь базовый преподавать =(

2017-07-19 14:23 UTC, zeckson commented on javascript.html
> +              <li>в функциях, которые не являются методами никакого объекта или класса не используется <code>this</code></li>
С большой буквы

2017-07-19 14:23 UTC, zeckson commented on javascript.html
> +              <li>Переменные, объявленные через <code>var</code> не удаляются оператором <code>delete</code></li>
Я бы вообще запретил `delete`

2017-07-19 14:23 UTC, zeckson commented on javascript.html
> +              <li>В коде нет объявленных, но неиспользуемых переменных. Проверка не относится к параметрам функций.</li>
`Проверка не относится к параметрам функций.`Почему нет?

2017-07-19 14:23 UTC, zeckson commented on javascript.html
> +            <h3 id="">Неиспользуемый код</h3>
Закомментированный код?

2017-07-19 14:23 UTC, zeckson commented on javascript.html
> +              <li>В конструкции <code>try..catch</code> запрещен пустой блок <code>try</code></li>
Пустой блок `catch`

2017-07-19 14:23 UTC, zeckson commented on javascript.html
> +              <li>В функциях не используются обращения к <code>caller</code> и <code>callee</code></li>
Перенести в запрещенное

2017-07-19 14:23 UTC, zeckson commented on javascript.html
> +              <li>При итерировании по объектам через <code>for..in</code> при работе со свойствами используется конструкция <code>hasOwnProperty</code></li>
`for..in` не используется

2017-07-19 14:23 UTC, zeckson commented on javascript.html
> +<pre class="language-js language-incorrect"><code>switch (val = getVal(), val) {}
это и так запрещено выше

2017-07-19 14:25 UTC, zeckson commented
> Аргументы и альтернатива. Давай не добавлять такую строку потому что это ложь, а вместо этого лучше напьемся

Без аргументов и альтернативы, просто предложение. Т.к. добавление такой строки приведет к дальнейшему бесконечному рефакторингу многочисленных мест.
Альтернативно я бы просто сделал сноску напротив всех пунктов где есть раздвоение, например `ES2015 и выше`

2017-07-19 14:27 UTC, o0 commented on javascript.html
> +              <li>при объявлении анонимных функций, скобки с параметрами ставятся непосредственно после ключевого слова function. Если функция именована, перед названием ставится пробел, после — нет.
@zeckson давай договоримся, что если ты что-то отрицаешь, то ты делаешь противопоставление, так удобней. Да, я мог ошибиться, но я не в контексте. Будет конструктивней, если ты напишешь: у нас не так, а _вот так_.

2017-07-19 14:27 UTC, zeckson commented on md/syntax.md
> +Трудоемкий и очень хрупкий процесс. Если хотя бы одна из переменных
А дописать предложение? Например, `давайте разберем на примере:` — нельзя же так обрывать предложение на пол-фразе

2017-07-19 14:27 UTC, o0 commented on javascript.html
> +              <li>После двоеточий и точек с запятым ставятся пробелы. Перед ними — не ставятся.</li>
Долой точки в конце

2017-07-19 14:27 UTC, zeckson commented on md/syntax.md
> +# Стиль кода JS
Не понял. А остальные `md`? Или о чем это? Это что-то другое?

2017-07-19 14:28 UTC, o0 commented on javascript.html
> +              <li>В качестве символа строки используется стандартный символ, который используется в системе</li>
EOL. LF/CRLF и вот это все.

2017-07-19 14:29 UTC, o0 commented on javascript.html
> +              <li>Все точки с запятой должны быть проставлены явно, не стоит рассчитывать на автоматическую расстановку точек с запятой ASI.</li>
Ну так ее называет ESLint, я читал их комментарии.
```js
a
++
b
```
Это резолвится механизмом ASI — automatic semicolon insertion. Давай дадим расшифровку.

2017-07-19 14:29 UTC, o0 commented on javascript.html
> +              <li>Не рекомендуется использовать указатель Unicode BOM в коде, потому что код должен быть сохранен не в кодировке UTF-16, а в кодировке UTF-8, в которой нет указателя порядка бит.</li>
Посоветуй ссылку?

2017-07-19 14:29 UTC, zeckson commented on md/syntax.md
> +#### Аргументы функций и вызовы через цепчку отделяются четырьмя пробелами
Мне, если честно всё равно я нажимаю заветную комбинацию клавиш и просто об этом не думаю. Нужно просто синхронизировать этот документ и `eslint`

2017-07-19 14:30 UTC, o0 commented on javascript.html
> +              <li>В условтях не используется небезопасное отрицание, например использование ! в in или instanceof без скобок.</li>
`code`

2017-07-19 14:30 UTC, o0 commented on javascript.html
> +              <li>Запрещено сравнение с NaN. Для проверки, является результат операции числовым, нужно использовать <code>isNaN</code>.</li>
Как ты считаешь?

2017-07-19 14:30 UTC, o0 commented on javascript.html
> +              <li>Запрещено использовать case без break или return в блоках switch.</li>
ESLint

2017-07-19 14:30 UTC, zeckson commented on md/syntax.md
> +#### Альтернативный способ переносить аргументы — выравнивать их с открывающей скобкой
> Java-Java.

Автореформаттеры ломают такой способ

2017-07-19 14:30 UTC, o0 commented on javascript.html
> +              <li>Если в функции используется ветвление, в котором есть возврат значения (<code>return</code>), <code>return</code> должен быть добавлен и в остальных ветках. Это правило предотвращае
Куда именно?

2017-07-19 14:31 UTC, o0 commented on javascript.html
> +        <article class="chapter-part">
Комментарий отправился не к тому, можешь уточнить что именно запрещено автоматически?

2017-07-19 14:31 UTC, zeckson commented on md/syntax.md
> +Положительный побочный эффект такого стиля заключается в том,
Ну тогда добавь такие пояснения везде. Почему так выборочно?

2017-07-19 14:31 UTC, o0 commented on javascript.html
> +              <li>Запрещено использовать множественное объявление через одно ключевое слово. Для каждой переменной используется отдельный <code>var</code>, <code>let</code> или <code>const</code>. Эт
Почему ты бы убрал примечания автора?

2017-07-19 14:32 UTC, o0 commented on javascript.html
> +              <li>Вместо вызова функции через <code>apply</code> используется spread-оператор</li>
Нет, вместо `Math.max.apply(null, arr)` делать `Math.max(...array)`. Надо написать подробней и с примером, ок.

2017-07-19 14:33 UTC, o0 commented on javascript.html
> +              <li>bind не используется вне методов классов</li>
А ну-ка, где это нам мешает. Это запрещает делать bind для просто функций, а внутри классов это пожалуйста. Может стоит переформулировать что в конструкторе это все делать можно. Мы уже дохрена базовых провели с этим правилом в ESLint.

2017-07-19 14:33 UTC, o0 commented on javascript.html
> +              <li>Переменные, объявленные через <code>var</code> не удаляются оператором <code>delete</code></li>
Запрети в ESLint, я добавлю

2017-07-19 14:33 UTC, o0 commented on javascript.html
> +            <h3 id="">Неиспользуемый код</h3>
А?

2017-07-19 14:34 UTC, o0 commented on javascript.html
> +              <li>В коде нет объявленных, но неиспользуемых переменных. Проверка не относится к параметрам функций.</li>
Ровно тот случай когда используется только третий параметр. Мы с тобой сами смотрели на правило, которое все это отменяет. Но если тебе не нравится давай поправим конфиг так, как ты считаешь нужным.

2017-07-19 14:34 UTC, o0 commented on javascript.html
> +              <li>В конструкции <code>try..catch</code> запрещен пустой блок <code>try</code></li>
`try`

2017-07-19 14:35 UTC, o0 commented on javascript.html
> +              <li>При итерировании по объектам через <code>for..in</code> при работе со свойствами используется конструкция <code>hasOwnProperty</code></li>
Правило?

2017-07-19 14:35 UTC, zeckson commented
> Ок, плохо, выход какой? Никаких альтернатив не предложено. Повздыхали и разошлись.

Я отревьюил как смог, но `html` форматирование мешает сосредоточиться на тексте к сожалению. Формат `html` плохо подходит для редактуры на мой взгляд. Плюс он не подразумевает модульности

2017-07-19 14:35 UTC, o0 commented on javascript.html
> +              <li>В функциях не используются обращения к <code>caller</code> и <code>callee</code></li>
Где у нас запрещенное?

2017-07-19 14:35 UTC, o0 commented on javascript.html
> +<pre class="language-js language-incorrect"><code>switch (val = getVal(), val) {}
Потерял контекст

2017-07-19 14:36 UTC, o0 commented
@zeckson согласен.

2017-07-19 14:38 UTC, zeckson commented on javascript.html
> +              <li>при объявлении анонимных функций, скобки с параметрами ставятся непосредственно после ключевого слова function. Если функция именована, перед названием ставится пробел, после — нет.
@o0 хорошо, у нас вот так:
```
'space-before-function-paren': ['error', {named: 'never', anonymous: 'always'}],
```

2017-07-19 14:39 UTC, zeckson commented on javascript.html
> +              <li>Все точки с запятой должны быть проставлены явно, не стоит рассчитывать на автоматическую расстановку точек с запятой ASI.</li>
Или ссылку или расшифровку. Лучше ссылку на расшифровку, например wiki.

2017-07-19 14:40 UTC, zeckson commented on javascript.html
> +              <li>Не рекомендуется использовать указатель Unicode BOM в коде, потому что код должен быть сохранен не в кодировке UTF-16, а в кодировке UTF-8, в которой нет указателя порядка бит.</li>
https://en.wikipedia.org/wiki/Byte_order_mark

2017-07-19 14:41 UTC, zeckson commented on javascript.html
> +              <li>Запрещено сравнение с NaN. Для проверки, является результат операции числовым, нужно использовать <code>isNaN</code>.</li>
`Number.isNaN()` лучше, т.к. не пытается приводить

2017-07-19 14:42 UTC, zeckson commented on javascript.html
> +              <li>Запрещено использовать case без break или return в блоках switch.</li>
Не могу найти такой рул. Подксажи, пожалуйста.

2017-07-19 14:42 UTC, zeckson commented on javascript.html
> +              <li>Если в функции используется ветвление, в котором есть возврат значения (<code>return</code>), <code>return</code> должен быть добавлен и в остальных ветках. Это правило предотвращае
после примеров

2017-07-19 14:44 UTC, zeckson commented on javascript.html
> +              <li>В конструкции <code>try..catch</code> запрещен пустой блок <code>try</code></li>
https://github.com/htmlacademy/eslint-config-htmlacademy/issues/12

2017-07-19 14:56 UTC, zeckson commented on javascript.html
> +              <li>В коде нет объявленных, но неиспользуемых переменных. Проверка не относится к параметрам функций.</li>
Сейчас проверяет всё:
```
 'no-unused-vars': ['error', {args: 'all', argsIgnorePattern: '^_'}], // check that all args are used¬
```

2017-07-19 14:56 UTC, zeckson commented on javascript.html
> +              <li>При итерировании по объектам через <code>for..in</code> при работе со свойствами используется конструкция <code>hasOwnProperty</code></li>
увы в `eslint` нет такого правила, но я бы запретил совсем

2017-07-19 14:56 UTC, zeckson commented on javascript.html
> +              <li>В функциях не используются обращения к <code>caller</code> и <code>callee</code></li>
344 строка https://github.com/htmlacademy/codeguide/pull/13/files/ea43097679bd6bf15812174a0234da38e2c79c9b#diff-7796c0b9f39eb4152e44c90da7a2ca9eR344

2017-07-19 14:56 UTC, zeckson commented on javascript.html
> +<pre class="language-js language-incorrect"><code>switch (val = getVal(), val) {}
нельзя присваивать и использовать одновременно

2017-07-19 14:56 UTC, zeckson commented on javascript.html
> +            <h3 id="">Неиспользуемый код</h3>
Ну про закомментированный код или это не сюда?

2017-07-19 14:56 UTC, zeckson commented on javascript.html
> +              <li>bind не используется вне методов классов</li>
Аааа это по `eslint`?! Блин, тогда это все меняет, давай сюда добавим ссылки на правила соответствующие?

2017-07-19 14:56 UTC, zeckson commented on javascript.html
> +              <li>Вместо вызова функции через <code>apply</code> используется spread-оператор</li>
Ну как-то да, т.к. `apply` и `call` тебе нужен, чтобы переопределить контекст

2017-07-19 14:56 UTC, zeckson commented on javascript.html
> +              <li>bind не используется вне методов классов</li>
А что это за правило, кстати?

2017-07-19 14:58 UTC, zeckson commented on javascript.html
> +              <li>В качестве символа строки используется стандартный символ, который используется в системе</li>
Тогда нужно написать в качестве символа **переноса** строки

2017-07-19 14:58 UTC, zeckson commented on javascript.html
> +              <li>Оператор вызова функции () не отделяется круглыми скобками от названия функции</li>
Забыл вопрос задать =)
Имется ввиду вот это: (callFun)()?

2017-07-19 15:01 UTC, zeckson commented on javascript.html
> +              <li>Запрещено использовать множественное объявление через одно ключевое слово. Для каждой переменной используется отдельный <code>var</code>, <code>let</code> или <code>const</code>. Эт
Они то есть то нет, т.е. есть куча правил, где я немного недоумевал, но там примечаний не было, а на других, где они не нужны по-моему есть. Речь идёт о consistency и правилах появления таких примечаний.
Давай их как минимум переносить в конец правила.

2017-07-19 15:02 UTC, zeckson commented on javascript.html
> +              <li>Переменные, объявленные через <code>var</code> не удаляются оператором <code>delete</code></li>
не могу запретить совсем, только для ES6 https://github.com/htmlacademy/eslint-config-htmlacademy/issues/19

2017-07-19 15:04 UTC, zeckson commented on javascript.html
> +        <article class="chapter-part">
```
+          <div class="chapter-part-col chapter-part-col--full-width">
 +            <h3 id="">Операторы</h3>
 +            <ul>
 +              <li>В конструкторе классов-наследников  обязательно вызывается super()</li>
 +
 +              <li>В конструкторе нет обращения к this до того, как будет вызван super()</li>
 +            </ul>
 +          </div>
 +        </article>
```

2017-07-19 15:42 UTC, o0 commented on javascript.html
> +              <li>Запрещено использовать множественное объявление через одно ключевое слово. Для каждой переменной используется отдельный <code>var</code>, <code>let</code> или <code>const</code>. Эт
Расскажи, где ты недоумевал и я там напишу примечания. Они нужны чтобы объяснить почему мы сделали именно такой выбор в правиле, что мы не пальцем в небо тыкали

2017-07-19 15:43 UTC, o0 commented on javascript.html
> +              <li>Вместо вызова функции через <code>apply</code> используется spread-оператор</li>
Но его можно и для этого использовать

2017-07-27 16:10 UTC, o0 commented on javascript.html
> +<pre class="language-js language-incorrect"><code>switch (val = getVal(), val) {}
Это немного не то!

2017-08-01 11:46 UTC, o0 commented on javascript.html
> +            <h3 id="">Неиспользуемый код</h3>
Не, про закомментированный код у нас нет ничего в этом гайде. ESLint же не умеет его проверять.

2017-08-01 11:46 UTC, o0 commented on javascript.html
> +<pre class="language-js language-incorrect"><code>switch (val = getVal(), val) {}
Разные правила, каждый пример взят по отдельному правилу, я не вспомню сейчас названия обоих. Это правило не про присвоение и использование, а про оператор `запятая` в условиях.

2017-08-01 13:17 UTC, zeckson commented on javascript.html
> +            <p>В конструкторе классов-наследников обязательно вызывается <code>super()</code></p>
Я повторю свой вопрос — нужно ли дублировать синтаксические ошибки в стайлгайде?

2017-08-01 13:17 UTC, zeckson commented on javascript.html
> +            <p>В конструкторе нет обращения к <code>this</code> до того, как будет вызван <code>super()</code></p>
Я повторю свой вопрос — нужно ли дублировать синтаксические ошибки в стайлгайде?

2017-08-01 13:21 UTC, zeckson commented on javascript.html
> +            <p>В конструкторе классов-наследников обязательно вызывается <code>super()</code></p>
Хотя ладно, пусть будет

2017-08-01 13:21 UTC, zeckson commented on javascript.html
> +            <p>В конструкторе нет обращения к <code>this</code> до того, как будет вызван <code>super()</code></p>
Хотя ладно, пусть будет

2017-08-01 13:21 UTC, zeckson approved these changes

2017-08-01 14:14 UTC, o0 commented on javascript.html
> +            <p>В конструкторе нет обращения к <code>this</code> до того, как будет вызван <code>super()</code></p>
Правило ESLint! Тулза проверяет, хороший ли синтаксис, у них есть такие правила, например проверка валидности регулярки. Если регулярка невалидна, то код упадет, но ESLint не позволяет до этого дойти, так что, я считаю, что это хорошо.

2017-08-01 14:17 UTC, merged