Добавляет обновленную версию кодгайда с JS
htmlacademy/codeguide pull request #16
Opened 2017-08-01 16:09 UTC by o0

2017-08-01 19:33 UTC, zeckson requested changes

2017-08-01 19:33 UTC, zeckson commented on javascript.html
> +            <h3 id="">Отступы, пробелы и переносы</h3>
`id=""`

2017-08-01 19:33 UTC, zeckson commented on javascript.html
> +            <h3 id="">Строки</h3>
`id=""`

2017-08-01 19:33 UTC, zeckson commented on javascript.html
> +            <h3 id="">Числа</h3>
`id=""`

2017-08-01 19:33 UTC, zeckson commented on javascript.html
> +            <h3 id="">Литералы</h3>
`id=""`

2017-08-01 19:33 UTC, zeckson commented on javascript.html
> +            <h3 id="">Операторы</h3>
`id=""`

2017-08-01 19:33 UTC, zeckson commented on javascript.html
> +            <h3 id="">Условные операторы</h3>
`id=""`

2017-08-01 19:33 UTC, zeckson commented on javascript.html
> +            <h3 id="">Функции</h3>
`id=""`

2017-08-01 19:33 UTC, zeckson commented on javascript.html
> +            <h3 id="">Операторы</h3>
`id=""` — короче, посмотри сам дальше, там полно этого барахла

2017-08-02 10:57 UTC, o0 commented
@zeckson??

2017-08-02 10:59 UTC, zeckson approved these changes

2017-08-02 11:02 UTC, merged