Убирает противоречия eslint и стайлгайда Академии в пользу первого
htmlacademy/codeguide pull request #37
Opened 2020-08-27 11:57 UTC by levallevchenko

2020-08-27 12:01 UTC, levallevchenko commented on javascript.html
> +            <p>Обязательно переносить запятую на новую строку при объявлении массивов и объектов. Обязательно использовать запятую в конце списков, объектов или перечислений параметров функции</p>
У этих двух предложений разный смысл? Может их нужно местами поменять.

2020-09-17 08:28 UTC, sashasushko requested changes

2020-09-17 08:28 UTC, sashasushko commented on javascript.html
> +            <p>Все переменные должны быть названы в верблюжьем регистре (camelCase). Исключения составляют константы которые должны именоваться прописными буквами в змеином регистре (UPPER_SNAKE_CASE
```suggestion
            <p>Все переменные должны быть названы в верблюжьем регистре (camelCase). Исключения составляют константы которые должны именоваться прописными буквами в константном регистре (CONSTANT_CASE) и названия классов, функций-конструкторов и перечислений, которые именуются с заглавной буквы (PascalCase)</p>
```

2020-09-17 08:28 UTC, sashasushko commented on javascript.html
> +            <p>Обязательно переносить запятую на новую строку при объявлении массивов и объектов. Обязательно использовать запятую в конце списков, объектов или перечислений параметров функции</p>
```suggestion
            <p>Обязательно переносить запятую на новую строку при объявлении массивов и объектов. Обязательно использовать запятую в конце списков, объектов или перечислений параметров функции</p>
            <pre class="language-js language-incorrect"><code>var foo = {
    a: 1,
    b: 2
};

var bar = [
    1,
    2
];</code></pre>
<pre class="language-js language-correct"><code>var foo = {
    a: 1,
    b: 2,
};

var bar = [
    1,
    2,
];</code></pre>
```

2020-09-17 08:28 UTC, sashasushko commented on javascript.html
> +            <p>Код работает в строгом режиме: в начале всех файлов явно прописана директива <code>'use strict'</code> или используются модули ECMAScript, которые по умолчанию работают в строгом режим
```suggestion
            <p>Код работает в строгом режиме: в начале всех файлов явно прописана директива <code>"use strict"</code> или используются модули ECMAScript, которые по умолчанию работают в строгом режиме</p>
```

2020-09-17 09:46 UTC, levallevchenko commented
@sashasushko мёржить?

2020-09-17 10:11 UTC, sashasushko commented
@levallevchenko нет пока

2020-09-17 10:12 UTC, levallevchenko commented
ok :)

2020-09-17 10:26 UTC, merged