Обновляет лого для JS
htmlacademy/codeguide pull request #53
Opened 2021-02-19 13:46 UTC by nikolai-shabalin

2021-02-20 09:02 UTC, sashasushko requested changes
Кажется, что лого другое должно быть - [без цифры](https://gibecdn.azureedge.net/media/1350/front-end-2-1280x780.png)

2021-02-20 10:22 UTC, nikolai-shabalin commented
Это не цифра, это буква `S`.  Тот логотип с `JS` имеет другие пропорции. То есть чтобы его использовать нужно будет и HTML менять

2021-02-20 10:26 UTC, sashasushko approved these changes

2021-02-20 10:28 UTC, nikolai-shabalin commented
Это всё из-за надписи над логотипом `html` =(

2021-02-20 12:12 UTC, sashasushko commented
Так может бахнем сразу троицу, как по моей ссылке? HTML и CSS пусть ведут на вашу часть, JS - на нашу

2021-02-24 08:34 UTC, nikolai-shabalin commented
Давай так

2021-06-22 17:17 UTC, nikolai-shabalin commented
@sashasushko обновил

2021-10-27 06:55 UTC, AntonovIgor requested changes

2021-10-27 06:55 UTC, AntonovIgor commented on index.html
> +              <img src="img/icon-css.svg"  width="200" height="200"  alt="Логотип CSS">
```suggestion
              <img src="img/icon-css.svg" width="200" height="200" alt="Логотип CSS">
```

2021-10-27 06:55 UTC, AntonovIgor commented on index.html
> +              <img src="img/icon-css.svg"  width="200" height="200"  alt="Логотип CSS">
@nikolai-shabalin лишние пробелы появились.

2021-10-27 07:14 UTC, sashasushko commented
Всё забываю ответить: давайте JS-лого оставим квадратным, а CSS и HTML сопоставимые по высоте, и ничего что они тогда будут шире.

2021-10-27 12:27 UTC, sashasushko commented
Закинул коммит, чтобы было понятно, о чём я.

2021-10-27 13:51 UTC, nikolai-shabalin commented
Ага, подмёржил мастер. Конфликты были. Давайте мёржить?

2021-10-27 13:58 UTC, sashasushko approved these changes

2021-10-27 15:03 UTC, merged